name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: setup git config
        run: |
          git config --global user.email "bartek0894@gmail.com"
          git config --global user.name "bpiasecki"
          
      - name: Prepare and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install --legacy-peer-deps
          npm run ng -- deploy --base-href=/money-manager/ --no-silent
